# Generated by Django 4.2.6 on 2023-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_position_x', models.IntegerField(blank=True, null=True)),
                ('ball_position_y', models.IntegerField(blank=True, null=True)),
                ('player_1_position_x', models.IntegerField(blank=True, null=True)),
                ('player_1_position_y', models.IntegerField(blank=True, null=True)),
                ('player_2_position_x', models.IntegerField(blank=True, null=True)),
                ('player_2_position_y', models.IntegerField(blank=True, null=True)),
                ('game_status', models.CharField(blank=True, max_length=50, null=True)),
                ('player_1_id', models.IntegerField(blank=True, null=True)),
                ('player_1_name', models.CharField(blank=True, max_length=300, null=True)),
                ('player_1_score', models.IntegerField(blank=True, null=True)),
                ('player_2_id', models.IntegerField(blank=True, null=True)),
                ('player_2_name', models.CharField(blank=True, max_length=300, null=True)),
                ('player_2_score', models.IntegerField(blank=True, null=True)),
                ('game_rule', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
